import 'package:flutter/material.dart';

import '../../design_system/ds_theme.dart';

/// Global themes for Smart App Lock — the light/dark foundations.
///
/// Both are generated by the design system ([DsThemes.build]) from the
/// same token set, so light and dark can never drift apart.
abstract final class AppTheme {
  static ThemeData get light => DsThemes.build(Brightness.light);

  static ThemeData get dark => DsThemes.build(Brightness.dark);
}
